### ISSUE TITLE
Allow for other ways to trigger the "Hidden" functionality in the module

### ISSUE THREAD

**Issue by feltz916** [gludington/conditional-visibility#15]
Currently, its painstakingly long for players to hide, and there is no way (that i am aware of) to be able to trigger this functionality outside of the Token HUD icon selection.

**Preferred option:**
Allow an option for integration into the dnd5e rule system, that when a stealth roll is made, the "Hidden" functionality of this module is executed.

**Optional:**
Allow for a macro to call the "Hidden" function directly, incase preferred option is too difficult and/or not possible.

**Comment by gludington** [comment]
On the macro side of things, I have this sort of API in the works:

ConditionalVisibility.set(tokens, conditionname, true/false);
where the condition name is one of the true/false conditions, e.g. invisible

Hide is a little different, because it needs a value
ConditionalVisibility.hide(tokens, value);
where value can be a flat number to apply to all tokens.  If missing, each token rolls its stealth roll
ConditionalVisibility.unhide(tokens);
removes the hidden condition

Any comments on/problems with/suggestions for that sort of usage?

**Comment by feltz916** [comment]
Hey, i think this will be good enough for the macro support. It would at least allow me to tell give players a "Stealth" macro that interacts with hide.

Long term it would be very nice if it could hook into character sheet rolls somehow, and set the hide value when a player rolls "Stealth" via character sheet and set the value that way (in case they have advantage or disadvantage)

**Comment by gludington** [comment]
The long term issue seems to be one of module compatibility more than anything; I believe i have it working (in the macros branch, if this is something you like to look at) for vanilla FoundryVTT rolls, but modules that replace the rolling mechanism do not have the same hooks.   I will be talking to them as I find them; is there a particular rolling module you use, or do you use stock Foundry?

**Comment by feltz916** [comment]
Oh wow. Personally, I only use Midi-QOL module which i believe replaces the rolling mechanism. I don't use it for any automation, just to combine the chat cards for attack and damage in the chat window.
